[[FreeBSDSysroot]]
arch = "x86_64"
git-tree-sha1 = "654e8818dd4104ace355e93b889ef6f3299e1c3e"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "5de1ee63b2ef832b2af1720d0bd708bddcbf305f65b491892669c66d8836f876"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot]]
arch = "aarch64"
git-tree-sha1 = "a3cdc473006b24264400fdf002085decac0cec8f"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "c39041fafa0721fde26502b1bc405c09272bbb03fee58c1598d4042649d20d24"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-build_log]]
arch = "x86_64"
git-tree-sha1 = "9afa3dd5a10a9a7b431b3ddbb7cabc9035564e75"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "9a19765a7dd54c4b3bb17c12a1d79429cc82ea50726ea2095183a217f83cab92"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-build_log]]
arch = "aarch64"
git-tree-sha1 = "f854d9bf3698268e9708dd940e70bbe5d03b2812"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "baac0138b53075571a0c5fd6af62f5fc47ca0c93d424fbe7ee314cbd441db8d9"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-extract_log]]
arch = "x86_64"
git-tree-sha1 = "51271bbc25b146ad66583e22d52e4d4f6c3a94ae"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "9a28813a353dc9c282de65391967dc6260f7ad7ec59a0a49ff5a3245fadde486"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-extract_log]]
arch = "aarch64"
git-tree-sha1 = "505d48aed0c2189761b6bdcf4f9bb880ee183af2"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "3a823e5815dc2d5acb6e0647987cf7aa4b18667bd340fb393313bd3219663794"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
