[[FreeBSDSysroot]]
arch = "x86_64"
git-tree-sha1 = "654e8818dd4104ace355e93b889ef6f3299e1c3e"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "f1666ec4f82804f52df2e262799690324393081df72178b288b039b9456a091f"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot]]
arch = "aarch64"
git-tree-sha1 = "a3cdc473006b24264400fdf002085decac0cec8f"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "8d798b84a642d0edc88fdbaa1e10f7f1e2e1a850e42a992a2ad4f6d3528c25d9"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-build_log]]
arch = "x86_64"
git-tree-sha1 = "673b9b26e7b4c43003dc2ed04123e92025c1a7f6"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "48813bcf352ef1cbd3e994d88aa8329b0a9117f2c8c738838f90298d262830a4"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-build_log]]
arch = "aarch64"
git-tree-sha1 = "fa6340adea2ec75c9725cc99c91af30d5a821a4f"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "32d8bb843ec06eb77a471b5c22b4455401f4d03564a21396de73c62316b18454"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-extract_log]]
arch = "x86_64"
git-tree-sha1 = "0503faf480bba758d0a0a4cac534cf4763755e0e"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "09ab10c01cb8af454b5281588ddde9de3bbde26155c3a164f4d2fe6504885e15"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-extract_log]]
arch = "aarch64"
git-tree-sha1 = "9605a2f4c208aed584f302c4e731c402f7e608c2"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "161ea79d5a69ff010d620cdc5e874739aa29308f75022cb73e7fb7e46c2c4496"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
