[[FreeBSDSysroot]]
arch = "x86_64"
git-tree-sha1 = "654e8818dd4104ace355e93b889ef6f3299e1c3e"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "16574b9f7c9c47e7162ffbdf7c6abb021e6ada574ffd3dedee60ffd3001a2d56"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot]]
arch = "aarch64"
git-tree-sha1 = "a3cdc473006b24264400fdf002085decac0cec8f"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "e5e533a0bcf7a6eba14a7e966871e359b77bbf0b5e887955427d189adcb7ba79"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-build_log]]
arch = "x86_64"
git-tree-sha1 = "1db24a10b497687704b15ee2804adaecccf0802e"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "198e4f690c1affac5352a8022017057dd57497acfa73003495107b7cb19131af"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-build_log]]
arch = "aarch64"
git-tree-sha1 = "c15e5b70d08b2b27a5df1797ab0b92a71cc8f152"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "e4a28cbdbbd08f1e32414f57234ec14d2c0783bcfe2fae7c915416af99e53211"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4fce585dd71e61f27c032b3376ac0d95aaf7e82c"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "e8141d29899228aa36cf4aec509a4d748b072ee5568359be176f7d67cb6c0f12"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-extract_log]]
arch = "aarch64"
git-tree-sha1 = "0bd74f31017b2185c76b2ad6d03c1ea358426e7c"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "b4cf466643ccb8f2e799d03e79bd14abfe807cca11df29e371ce3e5df0bffc4d"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
