[[FreeBSDSysroot]]
arch = "x86_64"
git-tree-sha1 = "654e8818dd4104ace355e93b889ef6f3299e1c3e"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "79fe696f7e8c7cbdff698b4d925cee6b8d64b339c77ea8035881cf8f91963fae"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot]]
arch = "aarch64"
git-tree-sha1 = "a3cdc473006b24264400fdf002085decac0cec8f"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "715a3b6b9e0872bcb417f0c49c1d0e028ab0b9bccb996143a8710ad681c23d51"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-build_log]]
arch = "x86_64"
git-tree-sha1 = "4e21db0dc7e8a002cdee15557badff0de03ef3ac"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "e11a043f666578a8777cd36e1480ba01c674fc13cfce6060456dd4de7da2d616"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-build_log]]
arch = "aarch64"
git-tree-sha1 = "b8e7e4bef0c286d95990e31a56a73f1c4eaedf0d"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "c572086f30c0f26daba02f35301cae51b9ccd8a313ee55e37c3f5588210a2128"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1cfc83558cf6feab5ae8ff1956063071903c10d5"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "8d2bbbde725b5b1e5b6ec588a2089ba2a79f113a2784e35686bba15484039205"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f81592f2444a2894a44179f000c3931c095f8f97"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "3392c98eb49d28834d1d97bea291b6e35e70e913e3f26ed9eb0e5dff731aedfc"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
